services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - private

  backend-ws:
    build: ./backend
    ports:
      - "8765:8765"
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=ws
      - MISTRAL_CTX=8192
      - GPTOSS20B_CTX=80000
      - DEEPSEEKERR1_CTX=8192
      - RESPONSE_TOKENS=1024
      - DEBUG=on
    volumes:
      - ./tokenizers:/tokenizers
    command: ["python", "app_chat.py"]
    #command: ["tail", "-f", "/dev/null"]
    networks:
      - private

  backend-http:
    build: ./backend
    ports:
      - "9765:9765"
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=http
      - MISTRAL_CTX=8192
      - GPTOSS20B_CTX=80000
      - DEEPSEEKERR1_CTX=8192
      - RESPONSE_TOKENS=1024
      - DEBUG=on
    volumes:
      - ./tokenizers:/tokenizers
    command: ["python", "app_chat.py"]
    networks:
      - public
      - private
      - erebus_shared

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-ws
      - backend-http
    networks:
      - public
      - private
      - erebus_shared

volumes:
  ollama_data:

networks:
  public:
    driver: bridge
    internal: false
  private:
    driver: bridge
    internal: true
  erebus_shared:
    external: true
